theme: jekyll-theme-cayman
title: AppNext Project
description: everything you need to start your own next generation application 
github:
  repository_url: https://github.com/appnextdev/app-next-core 
  repository_name: AppNext Core
